<?php

/**
 * @file 
 * Provides an image effect for adding text to an image as an overlay, using a text field 
 * as source in the same file entity.
 */

/**
 * Implements hook_image_effect_info().
 */
function image_entity_overlay_image_effect_info() {
  $effects = array();
  $effects['image_entity_overlay'] = array(
    'label' => t('Text overlay'),
    'help' => t('Add text to the image as an overlay, using a text field as source in the same file entity.'),
    'effect callback' => 'image_entity_overlay_effect',
    'form callback' => 'image_entity_overlay_form',
  );
  return $effects;
}

/**
 * Image effect callback; add text to the image as an overlay.
 */
function image_entity_overlay_effect(&$image, $data) {
  // If we're manipulating the sample image, we have to provide a sample text,
  // because there is no file entity in this case.
  if ($image->source == 'modules/image/sample.png') {
    $text = t('Sample text');
  }
  else {
    $files = entity_load('file', FALSE, array('uri' => $image->source));
    $file = !empty($files) ? reset($files) : FALSE;
    $text = token_replace($data['text'], array('file' => $file));
  }
  
  $textimage_preset = _textimage_preset_load('Alpha');
  $textimage_resource = textimage_image_from_preset($textimage_preset, check_plain($text));
  $text_width = imagesx($textimage_resource);
  $text_height = imagesy($textimage_resource);
  
  imagealphablending($image->resource, TRUE);
  imagecopy($image->resource, $textimage_resource, 5, 5, 0, 0, $text_width, $text_height);
  return TRUE;
}

/**
 * Implements hook_entity_update().
 */
function image_entity_overlay_entity_update($entity, $type) {
  if ($type == 'file' && $entity->type == 'image') {
    image_path_flush($entity->uri);
  }
}

/**
 * Form builder; configuration settings for the text overlay effect.
 */
function image_entity_overlay_form($data) {
  $form = array();
  
  $result = db_query("SELECT pid, name FROM {textimage_preset} ORDER BY name");
  $preset_list = array();
  foreach ($result as $preset) {
    $preset_list[$preset->pid] = $preset->name;
  }
  if (empty($preset_list)) {
    drupal_set_message(t('<a href="@add-preset">A Textimage preset</a> is needed to use this image effect.', 
      array('@add-preset' => url('admin/config/media/textimage/preset/new'))), 'warning');
  }
  
  $form['overlay_text_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Overlay Text Settings'),
  );
  $form['overlay_text_settings']['textimage_preset'] = array(
    '#type' => 'select',
    '#title' => t('Textimage preset'),
    '#options' => $preset_list,
    '#default_value' => isset($data['overlay_text_settings']['textimage_preset']) ? 
      $data['overlay_text_settings']['textimage_preset'] : '',
    '#description' => t('One of <a href="@presets">the Textimage presets</a> to be used for rendering the text.',
      array('@presets' => url('admin/config/media/textimage'))),
    '#required' => TRUE,
  );
  $form['overlay_text_settings']['text'] = array(
    '#type' => 'textfield',
    '#title' => t('Text'),
    '#description' => t('The text to use when place overlay onto the image.'),
    '#default_value' => isset($data['overlay_text_settings']['text']) ? 
      $data['overlay_text_settings']['text'] : '',
    '#required' => TRUE,
    '#size' => 90,
  );
  $form['overlay_text_settings']['replacement_patterns'] = array(
    '#type' => 'fieldset',
    '#title' => t('Replacement patterns'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['overlay_text_settings']['replacement_patterns']['tokens'] = array(
    '#theme' => 'token_tree',
    '#token_types' => array('file'),
  );
  $form['position_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Position Settings'),
  );
  $form['position_settings']['position'] = array(
    '#title' => t('Position'),
    '#type' => 'radios',
    '#options' => array(
      'bottom-left' => t('Bottom left'),
      'bottom-right' => t('Bottom right'),
      'top-left' => t('Top left'),
      'top-right' => t('Top right'),
    ),
    '#description' => t('Text overlay position on the image.'),
    '#default_value' => isset($data['position_settings']['position']) ? 
      $data['position_settings']['position'] : 'bottom-left',
    '#required' => TRUE,
  );
  $form['position_settings']['x_offset'] = array(
    '#type' => 'textfield',
    '#title' => t('X offset'),
    '#description' => t('Distance from the left/right margin of the image in pixels.'),
    '#default_value' => isset($data['position_settings']['x_offset']) ? 
      $data['position_settings']['x_offset'] : 10,
    '#required' => TRUE,
    '#size' => 3,
  );
  $form['position_settings']['y_offset'] = array(
    '#type' => 'textfield',
    '#title' => t('Y offset'),
    '#description' => t('Distance from the bottom/top margin of the image in pixels.'),
    '#default_value' => isset($data['position_settings']['y_offset']) ? 
      $data['position_settings']['y_offset'] : 10,
    '#required' => TRUE,
    '#size' => 3,
  );
  return $form; 
}
 